In [1]:
import numpy as np

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
#ilk satır 1:4 elemanları

[7 8 9]


In [3]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])
# birinci kısım satırları seçiyor, ikinci kısım elemanları 
# 0:2 satırlar 2. elemanları

[3 8]


In [4]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [5]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [6]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(str)

print(newarr)
print(newarr.dtype)

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)



['1.1' '2.1' '3.1']
<U32
[1 2 3]
int64


In [7]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype("i")

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
#Differance between copy and view
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
#orginal values cant show their base

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)

print(y.base)

None
[1 2 3 4 5]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
'''Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

Example
Convert the array into a 1D array:
'''
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [13]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr:
  print(x)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [14]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [19]:
arr = np.array([1, 2, 3, 4])

# np.nditer ile iterasyon sırasında elemanları float veri tipine dönüştürüyoruz
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['float']):
    print(x)

1.0
2.0
3.0
4.0


In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [21]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [22]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [23]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [24]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [25]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
# hstack() to stack along rows.
arr1 = np.array([[1, 2, 3],[1, 8, 3]])

arr2 = np.array([[4, 5, 6],[2, 4, 5]])

arr = np.hstack((arr1, arr2))

print(arr)

[[1 2 3 4 5 6]
 [1 8 3 2 4 5]]


In [36]:
# vstack() to stack along columns.

arr1 = np.array([[1, 2, 3],[1, 8, 3]])

arr2 = np.array([[4, 5, 6],[2, 4, 5]])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [1 8 3]
 [4 5 6]
 [2 4 5]]


In [37]:
# dstack() to stack along height, which is the same as depth.

arr1 = np.array([[1, 2, 3],[1, 8, 3]])

arr2 = np.array([[4, 5, 6],[2, 4, 5]])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]

 [[1 2]
  [8 4]
  [3 5]]]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 6)

print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [43]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)
# An alternate solution is using hsplit() opposite of hstack()

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)
#Find the indexes where the values are even: 

(array([1, 3, 5, 7]),)


In [51]:
arr = np.array([6, 7, 8, 9,7])

x = np.searchsorted(arr, 7)

print(x)

1


In [57]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [58]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


searchsorted yerini bulmuyor sıralı olduğu durumda, eleman nereye gelmeli onu buluyor

In [59]:
arr = np.array([15, 38, 41, 46])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2]),)


In [64]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [65]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [66]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [70]:
arr = np.array([False,2,"Zapple","Apple"])
print(np.sort(arr))

['2' 'Apple' 'False' 'Zapple']


In [71]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


Numpy Filtering

In [72]:
arr = np.array([41, 42, 43, 44])

x = arr[[True, False, True, False]]

print(x)

[41 43]


In [73]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [76]:
arr = np.array([1,24,53,6,436,643,31,93,49])
arr_filter = []

for element in arr:
    if element%3 == 0:
        arr_filter.append(True)
    else:
        arr_filter.append(False)

print(arr_filter)
print(arr[arr_filter])

[False, True, False, True, False, False, False, True, False]
[24  6 93]


In [7]:
import numpy as np
arr = np.array([1,24,53,6,436,643,31,93,49])
arr2 = np.array([])

for element in arr:
    if element%3 == 0:
        arr2 = np.append(arr2,element)

print(arr2)


[24.  6. 93.]


In [83]:
arr = np.array([1,24,53,6,436,643,31,93,49])
arr2 = np.array([],dtype= int)

for element in arr:
    if element%3 == 0:
        arr2 = np.append(arr2,element)

print(arr2)

[24  6 93]


In [85]:
arr = np.array([1, 24, 53, 6, 436, 643, 31, 93, 49])
arr2 = np.empty(0, dtype=int)  # Boş bir numpy dizisi oluşturuyoruz

for element in arr:
    if element % 3 == 0:
        arr2 = np.concatenate((arr2, [element]))

print(arr2)


[24  6 93]


Üstteki 3 tanesini alternatif filtreleme yolu olarak yazdım 

In [8]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
