In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

ModuleNotFoundError: No module named 'numpy'

In [ ]:
np.__version__

'1.21.5'

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#0-D
arr0 = np.array(31)

#1-D
arr1 = np.array([1,2,3])

#2-D
arr2 = np.array([[1,2,3],[4,5,6]])

#3-D
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]  )

In [ ]:
print(arr0.ndim)
print(arr0)

0
31


In [ ]:
print(arr1.ndim)
print(arr1)

1
[1 2 3]


In [ ]:
print(arr2.ndim)
print(arr2)

2
[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr3.ndim)
print(arr3)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##### Ndmin

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3[0, 1, 2])


6


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1,-2]) 

Last element from 2nd dim:  9


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]

array([1, 2, 3, 4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[::2]

array([1, 3, 5, 7])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-5:-1]) 

[3 4 5 6]


### Slicing 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) 

[3 8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.dtype

dtype('int64')



    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [ ]:
arr = np.array(['apple', 'banana', 'cherry',"pinapple","melon","watermelon","ğşi"])

print(arr.dtype) 

<U10


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### Astype()

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [ ]:
import numpy as np

arr = np.array([-1, 1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True False  True]
bool


In [ ]:
a= [1,2,3]
b=a 
b[0] = 31
print(a)

[31, 2, 3]


In [ ]:
a= [1,2,3]
b=list(a) 
b[0] = 31
print(a)

[1, 2, 3]


In [ ]:
a= [1,2,3]
b=a.copy()
b[0] = 31
print(a)

[1, 2, 3]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


#### Advice

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = np.array(arr)
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y = arr
arr[0] = 42
y[1] = 31

print(arr)
print(x) 
print(y) 

[42 31  3  4  5]
[42 31  3  4  5]
[42 31  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x) 

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 

#The copy returns None.
#The view returns the original array.

None
[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
#Returns Copy or View?

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]




You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr) 

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    for j in i:
      print(j) 

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x,end="\n\n\n") 

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]




In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x) 

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([1.1, 2.2, 3.3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x) 

b'1.1'
b'2.2'
b'3.3'


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x,end= " ") 

print()

for x in np.nditer(arr[:, 0:2:]):
  print(x,end= " ")

1 3 5 7 
1 2 5 6 

## Joining NumPy Arrays

##### concatenate

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.array([[9, -8], [-7, -8]])

arr = np.concatenate((arr1, arr2,arr3), axis=1)

print(arr) 

[[ 1  2  5  6  9 -8]
 [ 3  4  7  8 -7 -8]]


##### stack

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr) 

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


## Split Into Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,5)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


### Splitting 2-D Arrays

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

for i in newarr:
    print(i,end="\n\n\n")

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]




In [ ]:
#alternate option

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Searching Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6, 7]),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x) 

(array([0, 2, 4, 6]),)


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 1)
y = np.searchsorted(arr, 8)
z = np.searchsorted(arr, 10)


print(x) 
print(y) 
print(z) 

0
2
4


In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x) 

2


In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]


## Sorting Arrays

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [ ]:
import numpy as np

arr = np.array([True, False, True, False])

print(np.sort(arr))

[False False  True  True]


In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 


[False, False, True, True]
[43 44]


In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr >= 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 


[False  True  True  True]
[42 43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True False  True False]
[2 4 6]


In [3]:
import numpy as np

values = [13,21,21,40,48,55,72]

x = np.ptp(values)

print(x)
#range 72-13 max-min

59


The quartiles (Q0,Q1,Q2,Q3,Q4) are the values that separate each quarter.

Between Q0 and Q1 are the 25% lowest values in the data. Between Q1 and Q2 are the next 25%. And so on.

    Q0 is the smallest value in the data.
    Q1 is the value separating the first quarter from the second quarter of the data.
    Q2 is the middle value (median), separating the bottom from the top half.
    Q3 is the value separating the third quarter from the fourth quarter
    Q4 is the largest value in the data.

Calculating Quartiles with Programming

Quartiles can easily be found with many programming languages.

Using software and programming to calculate statistics is more common for bigger sets of data, as finding it manually becomes difficult.

In [ ]:
import numpy

values = [13,21,21,40,42,48,55,72]

x = numpy.quantile(values, [0,0.25,0.5,0.75,1])

print(x)

Calculating Percentiles with Programming

Percentiles can easily be found with many programming languages.

Using software and programming to calculate statistics is more common for bigger sets of data, as finding it manually becomes difficult.

In [5]:
import numpy

values = [13,21,21,40,42,48,55,72]

x = numpy.percentile(values, 65)

print(x)

45.3


Calculating the Standard Deviation with Programming

The standard deviation can easily be calculated with many programming languages.

Using software and programming to calculate statistics is more common for bigger sets of data, as calculating by hand becomes difficult.
Population Standard Deviation

In [9]:
import numpy

values = [4,11,7,14]

x = numpy.std(values)

print(x)

3.8078865529319543


In [10]:
import numpy

values = [4,11,7,14]

x = numpy.std(values, ddof=1)

print(x)

4.396968652757639
