In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [2]:
np.__version__

'1.21.5'

In [3]:
type(arr)

numpy.ndarray

In [4]:
#0-D
arr0 = np.array(31)

#1-D
arr1 = np.array([1,2,3])

#2-D
arr2 = np.array([[1,2,3],[4,5,6]])

#3-D
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]  )

In [5]:
print(arr0.ndim)
print(arr0)

0
31


In [6]:
print(arr1.ndim)
print(arr1)

1
[1 2 3]


In [7]:
print(arr2.ndim)
print(arr2)

2
[[1 2 3]
 [4 5 6]]


In [8]:
print(arr3.ndim)
print(arr3)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##### Ndmin

In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [10]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3[0, 1, 2])


6


In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1,-2]) 

Last element from 2nd dim:  9


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[:4]

array([1, 2, 3, 4])

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[::2]

array([1, 3, 5, 7])

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-5:-1]) 

[3 4 5 6]


### Slicing 2-D Arrays

In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

[7 8 9]


In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) 

[3 8]


In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr.dtype

dtype('int64')



    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [20]:
arr = np.array(['apple', 'banana', 'cherry',"pinapple","melon","watermelon","ğşi"])

print(arr.dtype) 

<U10


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


### Astype()

In [23]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [24]:
import numpy as np

arr = np.array([-1, 1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True False  True]
bool


In [25]:
a= [1,2,3]
b=a 
b[0] = 31
print(a)

[31, 2, 3]


In [26]:
a= [1,2,3]
b=list(a) 
b[0] = 31
print(a)

[1, 2, 3]


In [27]:
a= [1,2,3]
b=a.copy()
b[0] = 31
print(a)

[1, 2, 3]


In [28]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


#### Advice

In [29]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [30]:
arr = np.array([1, 2, 3, 4, 5])
x = np.array(arr)
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y = arr
arr[0] = 42
y[1] = 31

print(arr)
print(x) 
print(y) 

[42 31  3  4  5]
[42 31  3  4  5]
[42 31  3  4  5]


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x) 

[31  2  3  4  5]
[31  2  3  4  5]


In [33]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 

#The copy returns None.
#The view returns the original array.

None
[1 2 3 4 5]


In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [39]:
#Returns Copy or View?

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]




You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr) 

[1 2 3 4 5 6]


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
    for j in i:
      print(j) 

1
2
3
4
5
6


In [44]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x,end="\n\n\n") 

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]




In [45]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [46]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x) 

1
2
3
4
5
6
7
8


In [47]:
arr = np.array([1.1, 2.2, 3.3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x) 

b'1.1'
b'2.2'
b'3.3'


In [48]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x,end= " ") 

print()

for x in np.nditer(arr[:, 0:2:]):
  print(x,end= " ")

1 3 5 7 
1 2 5 6 

## Joining NumPy Arrays

##### concatenate

In [49]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [50]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.array([[9, -8], [-7, -8]])

arr = np.concatenate((arr1, arr2,arr3), axis=1)

print(arr) 

[[ 1  2  5  6  9 -8]
 [ 3  4  7  8 -7 -8]]


##### stack

In [51]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]


In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr) 

[[1 2 3]
 [4 5 6]]


In [53]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [54]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) 

[[[1 4]
  [2 5]
  [3 6]]]


## Split Into Arrays

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr,5)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


### Splitting 2-D Arrays

In [58]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [59]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

for i in newarr:
    print(i,end="\n\n\n")

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]




In [60]:
#alternate option

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr) 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Searching Arrays

In [61]:
arr = np.array([1, 2, 3, 4, 5, 4, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6, 7]),)


In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x) 

(array([0, 2, 4, 6]),)


In [64]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 1)
y = np.searchsorted(arr, 8)
z = np.searchsorted(arr, 10)


print(x) 
print(y) 
print(z) 

0
2
4


In [65]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x) 

2


In [66]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]


## Sorting Arrays

In [67]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]


In [68]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [69]:
import numpy as np

arr = np.array([True, False, True, False])

print(np.sort(arr))

[False False  True  True]


In [70]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


In [71]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [81]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

[41 43]


In [82]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 


[False, False, True, True]
[43 44]


In [84]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr >= 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 


[False  True  True  True]
[42 43 44]


In [85]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

[False  True False  True False  True False]
[2 4 6]
