# What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

# Why use ufuncs?
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.



# What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

Add the Elements of Two Lists
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.
Without ufunc, we can use Python's built-in zip() method:


In [2]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [3]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


## How To Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.
inputs - the number of input arguments (armrays).
outputs - the number of output arrays.

In [5]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


Addition

The add() function sums the content of two arrays, and return the results in a new array.
Example
Get your own Python Server

Add the values in arr1 to the values in arr2:


In [1]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr) 

[30 32 34 36 38 40]


Subtraction

The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr) 

[-10  -1   8  17  26  35]


Multiplication

The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr) 

[ 200  420  660  920 1200 1500]


Division

The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr) 

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr) 

[ 1  6  3  0  0 27]


In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr) 

[         1000       3200000     729000000 6553600000000          2500
             0]


In [9]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr) 

[ 1  6  3  0  0 27]


Quotient and Mod

The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [10]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr) 

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [11]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr) 

[1 2 1 2 3 4]


Truncation

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [12]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr) 

[-3.  3.]


In [13]:
import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr) 

[-3.  3.]


In [20]:
import numpy as np

arr = np.around(3.1666, 3)
print(arr)

arr = np.around(3.1666, 2)
print(arr)

arr = np.around(3.1666, 1)
print(arr)

arr = np.around(3.1666)
print(arr)

3.167
3.17
3.2
3.0


In [21]:
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr) 

[-4.  3.]


In [22]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr) 

[-3.  4.]


In [23]:
import numpy as np

arr = np.arange(1, 10)

print(arr)

print(np.log2(arr))


[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [24]:
import numpy as np

arr = np.arange(1, 10)

print(arr)

print(np.log10(arr)) 

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [25]:
import numpy as np

arr = np.arange(1, 10)

print(arr)

print(np.log(arr)) 

#np.log perform log at the base e

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [28]:
# creating custom log func with frompyfunc 
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 10))


2.0


In [29]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr) 

[2 4 6]


In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2,arr1])

print(newarr) 
type(newarr)

18


numpy.int64

In [31]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr) 

[6 6]


Cummulative Sum

Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [32]:
import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x) 
#Returns: 24 because 1*2*3*4 = 24

24


In [39]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x) 
#1*2*3*4*5*6*7*8 = 40320

40320


In [40]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr) 

[  24 1680]


In [41]:
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr) 

[   5   30  210 1680]


Differences

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.


In [42]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr) 

[  5  10 -20]


In [44]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr) 
#[5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30

[  5 -30]


In [47]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=3)

print(newarr) 

[-35]


In [49]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)
#lcm(Lowest Common Multiple) means "ekok" in Turkish

12


Finding LCM in Arrays

To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.


In [51]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x) 

18


Finding GCD (Greatest Common Denominator) Means "ekok" in Turkish

The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [54]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x) 

3


Finding GCD in Arrays

To find the Highest Common Factor of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.


In [55]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x) 

4


Trigonometric Functions

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [56]:
import numpy as np

x = np.sin(np.pi/2)

print(x) 

1.0


In [57]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x) 

[1.         0.8660254  0.70710678 0.58778525]


In [58]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x) 

[1.57079633 3.14159265 4.71238898 6.28318531]


In [62]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.sin(np.radians(90))
y = np.sin(90)

print(x) 
print(y) 

1.0
0.8939966636005579


In [69]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x) 


[ 90. 180. 270. 360.]


Finding Angles

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [1]:
import numpy as np

x = np.arcsin(1.0)

print(x) 

1.5707963267948966


In [3]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x) 

5.0


Hipoerbolik fonksiyonlar https://www.w3schools.com/python/numpy/numpy_ufunc_hyperbolic.asp?goalId=ee5f020c-0423-408c-ad5a-bb9b9003889b

Create Sets in NumPy
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [4]:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


Finding Union
To find the unique values of two arrays, use the union1d() method.

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [7]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [8]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [17]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)
arr = np.array([1,2,3])


[1 2 5 6]
[1 3 6]
